version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: laundry_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laundry_db
      MYSQL_USER: laundry_user
      MYSQL_PASSWORD: laundry_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - laundry_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  laundry_network:
    driver: bridge
